remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Computational Music Creativity
description: Part II Generative Audio
header: false
include:
  - assets/css/style.css